### ISSUE TITLE
Add ability to concatenate path to the same class_name

### ISSUE THREAD

**Issue by bounty1342** [BirjuVachhani/spider#16]
Hi,

A nice feature will be to add several path to the same class, giving the prefix more meaning.
Please find an exemple below :
```
groups:
  - path: assets/images
    class_name: AssetsImages
    package: assets
    types: [.png, .jpg, .jpeg, .webp, .webm, .bmp]
  - path: assets/onboarding
    class_name: AssetsImages
    package: assets
    prefix:onboarding
    types: [.png, .jpg, .jpeg, .webp, .webm, .bmp]
```

Regards
