### ISSUE TITLE
References are not generating for assets with same file name.

### ISSUE THREAD

**Issue by vcrash** [BirjuVachhani/spider#36]
When assets with same file name are containing in different subdirectories reference will be generated only for a single asset.

```
groups:
  - paths:
      - assets
      - assets/subdir
    class_name: Images
    types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
```

Expecting references are generated for each asset with specified paths.

**Comment by BirjuVachhani** [comment]
Can you share file structure here?

**Comment by vcrash** [comment]
For example:
assets/logo.png
assets/profile/logo.png

**Comment by BirjuVachhani** [comment]
I see. Please share exact configuration file as well.

**Comment by vcrash** [comment]
`
# Generated by Spider

# Generates unit tests to verify that the assets exists in assets directory
generate_tests: true

# Use this to remove vcs noise created by the `generated` comments in dart code
no_comments: true

# Exports all the generated file as the one library
export: true

# This allows you to import all the generated references with 1 single import!
use_part_of: true

# Location where all the generated references will be stored
package: resources

groups:
  - paths:
      - assets
      - assets/profile
    class_name: Images
    types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
#  - path: assets/vectors
#    class_name: Svgs
#    package: res
#    types: [ .svg ]
`

**Comment by BirjuVachhani** [comment]
Because both of the files fall under the same group and we are using file names as dart reference names, it is most likely that it is being overridden because of the same name. While we can add some suffix (like img1 and img2) to the reference name, it is not ideal to do that. It also makes it hard for the user to identify which is which.

You can do 2 things here:

1. Create a separate group for sub dir.
```yml
groups:
  - path: assets
    class_name: Assets
  - path: assets/profile
    class_name: ProfileAssets
```

2. Rename file so it is no longer the same.

Let me know if this is helpful. Thanks.
