### ISSUE TITLE
Feature/add subgroups support

### ISSUE THREAD

**Issue by Sanlovty** [BirjuVachhani/spider#49]
# Subgroups support
## :interrobang: Questions  
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
[Described in pull-request.](https://github.com/BirjuVachhani/spider/pull/50)

**Describe alternatives you've considered**
We can talk about how we can best deal with that.

**Additional context**
 nothing.

## :scroll: Description
**I faced the problem of impossibility of adding different prefixes in conjunction with paths into the same class. I decided to propose a solution to this "problem" by changing the structure of config.**
### JSON
```json
{
  "generate_tests":true,
  "no_comments":true,
  "export":true,
  "use_part_of":true,
  "use_references_list": false,
  "package":"resources",
  "groups": [
      {
        "class_name": "Assets",
        "subgroups": [
          {
            "path": "assets/images",
            "types": [ "jpg" ],
            "prefix": "jpg"
          },
          {
            "path": "assets/images",
            "types": [ "png" ],
            "prefix": "png"
          }
        ]
      }
    ]
}
```
### YAML
```yaml
  generate_tests: true
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: resources
  groups:
    - class_name: Assets
      subgroups:
        - path: assets/images
          types: [ jpg ]
          prefix: jpg
        - path: assets/images
          types: [ png ]
          prefix: png
```
## :gear: Generated files
> Provided that in  `assets/images` were 3 files: (`test2.jpg`, `test1.png`, `test3.png`)
```dart
part of 'resources.dart';

class Assets{
  Assets ._();
  
  static const String jpgTest2 = 'assets/images/test2.jpg';
  static const String pngTest1 = 'assets/images/test1.png';
  static const String pngTest3 = 'assets/images/test3.png';
}
```

**Comment by BirjuVachhani** [comment]
I don't understand the example. It seems wrong to me. You can get the same results with current system except the prefix part.

**Comment by BirjuVachhani** [comment]
How important it is to have different prefixes for the same kind of files? in this case, `png` and `jpg` which are put in the same file and class eventually!

**Comment by Sanlovty** [comment]
> How important it is to have different prefixes for the same kind of files? in this case, `png` and `jpg` which are put in the same file and class eventually!

I'll give you an example in an hour. And also i have an idea how to prevent my changes from being breaking.

**Comment by BirjuVachhani** [comment]
@Sanlovty Thank you for providing more details.

1. This is a more suitable example. However the problem is still about prefixes. Current version does allow you to specify multiple paths to have all those refs under the same class. So you just want them to have different prefixes in your case. So only having a prefix map with paths would be enough but I somewhat like your solution. I do wanna alter it though.
- How about `sub_groups` instead of `subgroups`.
- `types` should be specified at group level if all of the sub groups have the same type. If a type is explicitly specified on subgroup then use that otherwise inherit from the main group.

2. This can be simplified

```yaml
groups:
  - class_name: Images
    package: images
    subgroups:
      - path: assets/images
        types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
```
with this: (the way it is currently! I don't wanna lose that!)
```yaml
groups:
  - path: assets/images
    class_name: Images
    package: images
    types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]
```
